import 'package:get/get.dart';

import '../../models/customer_model.dart';

class CustomerController extends GetxController{
  var customers = <Customer>[
    Customer(
      name: 'Michael Johnson',
      email: 'michaeljohnson@gmail.com',
      date: '20 August, 2024',
      phoneNumber: '321-654-9870',
      source: 'Social Media',
      addedBy: 'Team Lead',
      branch: 'Chicago',
      address: '789 Maple St, Chicago, IL 60614',
      crewLeader: 'John Doe',
      type: 'Residential',
      scheduler: 'Jane Doe',
      company: 'Johnson Inc.',
      projectName: 'Office Renovation',
      projectNumber: 'P12345',
      projectType: 'Interior',
      buildingType: 'Commercial',
      addressTwo: 'Suite 300',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60614',
      tax: 'Tax ID: 123456789',
      potential: 'High',
      note: 'VIP Client',
      owner: 'Michael Johnson',
    ),
    Customer(
      name: 'Emily Davis',
      email: 'emilydavis@gmail.com',
      date: '22 August, 2024',
      phoneNumber: '456-789-1230',
      source: 'Email',
      addedBy: 'Sales Rep',
      branch: 'San Francisco',
      address: '101 Pine St, San Francisco, CA 94105',
      crewLeader: 'Tom Smith',
      type: 'Commercial',
      scheduler: 'Alex Taylor',
      company: 'Davis Co.',
      projectName: 'New Store Setup',
      projectNumber: 'P67890',
      projectType: 'Exterior',
      buildingType: 'Retail',
      addressTwo: '',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94105',
      tax: 'Tax ID: 987654321',
      potential: 'Medium',
      note: 'Requires follow-up',
      owner: 'Emily Davis',
    ),
    Customer(
      name: 'Chris Wilson',
      email: 'chriswilson@gmail.com',
      date: '25 August, 2024',
      phoneNumber: '567-890-1234',
      source: 'Referral',
      addedBy: 'Marketing',
      branch: 'Seattle',
      address: '202 Oak St, Seattle, WA 98101',
      crewLeader: 'Jim Brown',
      type: 'Industrial',
      scheduler: 'Sarah Connor',
      company: 'Wilson Enterprises',
      projectName: 'Factory Expansion',
      projectNumber: 'P11223',
      projectType: 'Industrial',
      buildingType: 'Industrial',
      addressTwo: 'Building A',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
      tax: 'Tax ID: 123987456',
      potential: 'High',
      note: 'Urgent Project',
      owner: 'Chris Wilson',
    ),
    Customer(
      name: 'Olivia Brown',
      email: 'oliviabrown@gmail.com',
      date: '27 August, 2024',
      phoneNumber: '678-901-2345',
      source: 'Website',
      addedBy: 'Customer Service',
      branch: 'Houston',
      address: '303 Birch St, Houston, TX 77002',
      crewLeader: 'Bill Gates',
      type: 'Residential',
      scheduler: 'Elon Musk',
      company: 'Brown LLC',
      projectName: 'Home Renovation',
      projectNumber: 'P33445',
      projectType: 'Interior',
      buildingType: 'Residential',
      addressTwo: '',
      city: 'Houston',
      state: 'TX',
      zipCode: '77002',
      tax: 'Tax ID: 456789123',
      potential: 'Low',
      note: 'Pending Confirmation',
      owner: 'Olivia Brown',
    ),
    Customer(
      name: 'Ethan Miller',
      email: 'ethanmiller@gmail.com',
      date: '30 August, 2024',
      phoneNumber: '789-012-3456',
      source: 'Direct Call',
      addedBy: 'Admin',
      branch: 'Miami',
      address: '404 Cedar St, Miami, FL 33101',
      crewLeader: 'Steve Jobs',
      type: 'Commercial',
      scheduler: 'Mark Zuckerberg',
      company: 'Miller Group',
      projectName: 'Office Building',
      projectNumber: 'P55667',
      projectType: 'Exterior',
      buildingType: 'Commercial',
      addressTwo: '',
      city: 'Miami',
      state: 'FL',
      zipCode: '33101',
      tax: 'Tax ID: 789456123',
      potential: 'Medium',
      note: 'Review Contract',
      owner: 'Ethan Miller',
    ),
    Customer(
      name: 'Sophia Martinez',
      email: 'sophiamartinez@gmail.com',
      date: '02 September, 2024',
      phoneNumber: '890-123-4567',
      source: 'Trade Show',
      addedBy: 'Exhibitor',
      branch: 'Boston',
      address: '505 Elm St, Boston, MA 02108',
      crewLeader: 'Jeff Bezos',
      type: 'Industrial',
      scheduler: 'Sunday Pichai',
      company: 'Martinez Industries',
      projectName: 'Warehouse Upgrade',
      projectNumber: 'P77889',
      projectType: 'Industrial',
      buildingType: 'Industrial',
      addressTwo: 'Unit 12',
      city: 'Boston',
      state: 'MA',
      zipCode: '02108',
      tax: 'Tax ID: 321654987',
      potential: 'High',
      note: 'High Priority',
      owner: 'Sophia Martinez',
    ),
    Customer(
      name: 'James Anderson',
      email: 'jamesanderson@gmail.com',
      date: '05 September, 2024',
      phoneNumber: '901-234-5678',
      source: 'Networking Event',
      addedBy: 'Business Development',
      branch: 'Philadelphia',
      address: '606 Walnut St, Philadelphia, PA 19103',
      crewLeader: 'Larry Page',
      type: 'Residential',
      scheduler: 'Sergey Brain',
      company: 'Anderson Co.',
      projectName: 'Apartment Renovation',
      projectNumber: 'P99000',
      projectType: 'Interior',
      buildingType: 'Residential',
      addressTwo: '',
      city: 'Philadelphia',
      state: 'PA',
      zipCode: '19103',
      tax: 'Tax ID: 654321987',
      potential: 'Medium',
      note: 'Initial Contact',
      owner: 'James Anderson',
    ),
    Customer(
      name: 'Ava Thomas',
      email: 'avathomas@gmail.com',
      date: '08 September, 2024',
      phoneNumber: '012-345-6789',
      source: 'Advertising',
      addedBy: 'Creative Team',
      branch: 'Atlanta',
      address: '707 Pine St, Atlanta, GA 30303',
      crewLeader: 'Tim Cook',
      type: 'Commercial',
      scheduler: 'Satya awesome',
      company: 'Thomas Enterprises',
      projectName: 'Retail Space Buildout',
      projectNumber: 'P11234',
      projectType: 'Exterior',
      buildingType: 'Commercial',
      addressTwo: 'Suite 200',
      city: 'Atlanta',
      state: 'GA',
      zipCode: '30303',
      tax: 'Tax ID: 321987654',
      potential: 'High',
      note: 'Follow-up Scheduled',
      owner: 'Ava Thomas',
    ),
    Customer(
      name: 'Liam Jackson',
      email: 'liamjackson@gmail.com',
      date: '11 September, 2024',
      phoneNumber: '123-456-7891',
      source: 'Customer Referral',
      addedBy: 'Referral Program',
      branch: 'Denver',
      address: '808 Fir St, Denver, CO 80203',
      crewLeader: 'Marissa Mayer',
      type: 'Industrial',
      scheduler: 'Jack Ma',
      company: 'Jackson LLC',
      projectName: 'Manufacturing Facility',
      projectNumber: 'P22334',
      projectType: 'Industrial',
      buildingType: 'Industrial',
      addressTwo: '',
      city: 'Denver',
      state: 'CO',
      zipCode: '80203',
      tax: 'Tax ID: 987321456',
      potential: 'Medium',
      note: 'Awaiting Approval',
      owner: 'Liam Jackson',
    ),
    Customer(
      name: 'Mia White',
      email: 'miawhite@gmail.com',
      date: '14 September, 2024',
      phoneNumber: '234-567-8901',
      source: 'Online Form',
      addedBy: 'Online Support',
      branch: 'Dallas',
      address: '909 Spruce St, Dallas, TX 75201',
      crewLeader: 'Sheryl Sandberg',
      type: 'Residential',
      scheduler: 'Eric Schmidt',
      company: 'White Enterprises',
      projectName: 'Home Improvement',
      projectNumber: 'P44556',
      projectType: 'Interior',
      buildingType: 'Residential',
      addressTwo: '',
      city: 'Dallas',
      state: 'TX',
      zipCode: '75201',
      tax: 'Tax ID: 654987321',
      potential: 'Low',
      note: 'Needs Follow-Up',
      owner: 'Mia White',
    ),
    Customer(
      name: 'Noah Lee',
      email: 'noahlee@gmail.com',
      date: '17 September, 2024',
      phoneNumber: '345-678-9012',
      source: 'Personal Visit',
      addedBy: 'Field Agent',
      branch: 'San Diego',
      address: '1010 Birch St, San Diego, CA 92101',
      crewLeader: 'Meg Whitman',
      type: 'Commercial',
      scheduler: 'Michael Dell',
      company: 'Lee Ventures',
      projectName: 'Office Refurbishment',
      projectNumber: 'P66778',
      projectType: 'Exterior',
      buildingType: 'Commercial',
      addressTwo: '',
      city: 'San Diego',
      state: 'CA',
      zipCode: '92101',
      tax: 'Tax ID: 789123654',
      potential: 'High',
      note: 'Urgent Project',
      owner: 'Noah Lee',
    ),
  ].obs;


  void deleteCustomer(Customer customer) {
    customers.remove(customer);
  }
  var filteredCustomers = <Customer>[].obs;

  @override
  void onInit() {
    super.onInit();
    filteredCustomers.value = customers;
  }

  void filterCustomers(String query) {
    if (query.isEmpty) {
      filteredCustomers.value = customers;
    } else {
      filteredCustomers.value = customers
          .where((customer) =>
          customer.name.toLowerCase().contains(query.toLowerCase()))
          .toList();
    }
  }
}